[[restcomm-connect_configuration_options]]
= Automatic Configuration Options for RestComm-Connect

RestComm-Connect used two configuration files (restcomm.conf & advanced.conf) located at *$RESTCOMM_HOME/bin/restcomm*. directory.
At the continuation we are providing detailed explanation for each property available.

TIP: A lot of the options explained here are available for a RestComm-connect version >= 7.8.0.

===== Basic configuration options on restcomm.con File.

* Section *#Network configuration*. Information can be found http://documentation.telestax.com/connect/configuration/Starting%20Restcomm-Connect.html#start-restcomm-connect[HERE]
[source,bash]
----
#hostname of the server to be used at restcomm.xml. If not set the STATIC_ADDRESS will be used.
RESTCOMM_HOSTNAME=''

# Activate music on conference when participants==1
PLAY_WAIT_MUSIC='TRUE'
----

* Section *#Telscale MEDIA SERVER CONFIGURATION*.
[source,bash]
----
#Media server running external (different node than Restcomm)
MS_EXTERNAL=FALSE
#MEDIA SERVER COMPATIBILITY MODE (mms=Mobicents Media Server, xms=Dialogic XMS)
MS_COMPATIBILITY_MODE='mms'

#XMS IP ADDRESS or RMS IP ADDRESS if using different IP from RestComm
MS_ADDRESS=''
MS_NETWORK=''
MS_SUBNET_MASK=''

# Media Server RTP ports
MEDIASERVER_LOWEST_PORT=''
MEDIASERVER_HIGHEST_PORT=''
MEDIASERVER_EXTERNAL_ADDRESS=''
#Medias server MGCP ports
LOCALMGCP=2727
REMOTEMGCP=2427

# When working with external Media Server specify the location of the Recording files
RECORDINGS_PATH=''
#Other
USESBC=TRUE
#For in-Band DTMF
DTMFDBI='0'
#MGCP_TIMOUT
MGCP_RESPONSE_TIMEOUT=500
----

* Section *#outbound proxy configuration*.
[source,bash]
----
# Address for outbound calls
OUTBOUND_PROXY='' #Provide port if different than 5060
OUTBOUND_PROXY_USERNAME=''
OUTBOUND_PROXY_PASSWORD=''

# Outbound proxy for SMS
SMS_PREFIX='#' #For VoipInnovation you will need the '#' character for SMS Prefix
SMS_OUTBOUND_PROXY='' #Please provide port if different than 5060

----

* Section *#Restcomm SMPP integration*.
[source,bash]
----
# Connection details for SMPP Restcomm integration
SMPP_ACTIVATE='false'  		#default SMPP activate is always false. Set to true to activate SMPP
SMPP_SYSTEM_ID=''
SMPP_PASSWORD=''
SMPP_SYSTEM_TYPE=''
SMPP_PEER_IP=''	#use IP or DNS name of peer SMPP server
SMPP_PEER_PORT=''
SMPP_SOURCE_MAP=''
SMPP_DEST_MAP=''
SMPP_INBOUND_ENCODING=''
SMPP_OUTBOUND_ENCODING=''
----

* Section *#Restcomm DID provider integration*.
[source,bash]
----
# DID Provision provider variable declarations
PROVISION_PROVIDER=''  # values: BW (Bandwidth), NX (Nexmo), VB (Voxbone)
#Username and password for all supported DID provision providers
DID_LOGIN=''
DID_PASSWORD=''
----

* Section *#Text-to-speech*.
* Go to link:http://www.voicerss.org and get a Text-to-Speech account. This is a free account that is required to activate Text-to-Speech in Restcomm.
[source,bash]
----
# VoiceRSS variable declarations
VOICERSS_KEY=
----

* Section *#RestComm PORT configuration*.
[source,bash]
----
HTTP_PORT='8080' #Port used for HTTP. Default 8080
HTTPS_PORT='8443' #Port used for HTTPS. Default 8443
#Connectors port configuration
SIP_PORT_UDP='5080'		#LB UDP port. Default is 5080
SIP_PORT_TCP='5080'		#LB TCP port. Default is 5080
SIP_PORT_TLS='5081'		#LB TLS port. Default is 5081
SIP_PORT_WS='5082'		#LB WS port. Default is 5082
SIP_PORT_WSS='5083'		#LB WSS port. Default is 5083
#Port Offset Used when more that one RC is running on the same machine. To avoid port conflicts
#E.g. If set PORT_OFFSET='100' all configured ports will be accessible from PORT+100.
PORT_OFFSET='0' #Port offset configurations. Default '0'.
----

* Section *#LOGS level*.
[source,bash]
----
#Usual values : WARN,INFO,DEBUG
LOG_LEVEL='INFO' #Used for RMS & RC console-handler.
LOG_LEVEL_COMPONENT_GOVNIST='INFO' #Log level for "gov.nist" module
LOG_LEVEL_COMPONENT_SIPSERVLET='INFO' #Log level for "org.mobicents.servlet" module

#AKKA log level. Set the Log level for the AKKA actor system.
AKKA_LOG_LEVEL='INFO'
----

**For Advanced configuration options http://HERE[HERE]*
