To make Restcomm fully Secure, you need to configure both the Web Part (HTTP Connector) and the SIP Part (SIP Over WebSockets Secure Connector) :

[[enable-https-secure-connector]]
Enable HTTPs Secure Connector
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Restcomm uses port 8080 on HTTP connector by default. The following instruction will guide you through the steps required to configured SSL and enable HTTPS.

Make sure you are testing using the latest Restcomm. 


[[step-1]]
Step 1 - Keystore by Certificate Authority (CA)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Create a certificate keystore for the SSL connector. 
If you are using a Certificate Authority (CA), create the keystore following the instruction from your supplied by the provider CA.

[[step-2]]
Step 2 - Self-signed Certificate Keystore
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


To create a self-signed certificate keystore, perform the following steps:

[source,lang:default,decode:true]
----
$JAVA_HOME/bin/keytool -genkey -alias restcomm -keyalg RSA -keystore $RESTCOMM_HOME/standalone/configuration/restcomm.keystore
----

For this example, we shall use the password, "changeit". 

Also make sure that for first and last name (CN) you provide the hostname of the machine running Restcomm. Running the command should look like this:

[source,lang:default,decode:true]
----
Enter keystore password: changeit
Re-enter new password: changeit
What is your first and last name?
[Unknown]: HOSTNAME_HERE
What is the name of your organizational unit?
[Unknown]:
What is the name of your organization?
[Unknown]:
What is the name of your City or Locality?
[Unknown]:
What is the name of your State or Province?
[Unknown]:
What is the two-letter country code for this unit?
[Unknown]:
Is CN=HOSTNAME_HERE, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown correct?
[no]: yes

Enter key password for <restcomm>
(RETURN if same as keystore password): {JUST PRESS RETURN}
----

* HOSTNAME : Must match content of the  "/etc/hostname or /etc/hosts" file. 

Copy the generated self-signed keystore to the configuration directory as shown below

[source,lang:default,decode:true]
----
$RESTCOMM_HOME/standalone/configuration/restcomm.keystore
----


[[step-3]]
Step 3 - Configure Restcomm Configuration Files
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[source,lang:default,decode:true]
----
$RESTCOMM_HOME/bin/restcomm/restcomm.conf
----


[source,lang:default,decode:true]
----

#Allowed values FALSE, SELF, AUTH.
#If SELF set self-signed certificate will be created.
#If AUTH, Authorized certificate will be used.Need to place the certificate at "$RESTCOMM_HOME/standalone/configuration/"
#To Disable use 'FALSE'
SECURESSL=SELF

#HTTPS Settings
DISABLE_HTTP='false' #Control whether or not HTTP connector will be disabled. Values, true=HTTP connector will be disable, false=HTTP Connector will not be disabled
TRUSTSTORE_FILE='restcomm.jks' #File should be located at $RESTCOMM_HOME/standalone/configuration folder. Provide just the name of the trustore file. Leave it blank to disable HTTPS
TRUSTSTORE_PASSWORD='changeit' #Password for the trustore file
TRUSTSTORE_ALIAS='restcomm' #The certificate alias

----

If you are using a self-signed certificate, change the SSL_MODE value to SSL_MODE='allowall'
[source,lang:default,decode:true]
----
SSL_MODE='strict' #Control whether or not Restcomm will accept self-signed certificates. Values allowall=allow self-signed certificates, strict=don't allow self signed certificates
----

Go to the Restcomm Admin UI at the following URL

[source,lang:default,decode:true]
----
http://RESTCOMM_IP_ADDRESS:8443/
----

If you want to access HTTPS using the default port 443 instead of Restcomm' default 8443, change the following options in the $RESTCOMM_HOME/bin/restcomm/restcomm.conf file.

[source,lang:default,decode:true]
----
#RestComm PORT configuration
HTTP_PORT='8080' #Port used for HTTP. Default 8080
HTTPS_PORT='8443' #Port used for HTTPS. Default 8443

----





For any questions or suggestions, please use the following channels:

* Restcomm forum: https://groups.google.com/forum/#!forum/restcomm
* Stack Overflow: http://stackoverflow.com/questions/tagged/restcomm (remember to tag your questions with 'restcomm')
* Gitter #Restcomm-Discuss channel at https://gitter.im/RestComm/Restcomm-discuss
