[[add-g729-to-rms]]
Add G729 Codec to the Restcomm Media Server
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

IMPORTANT: Restcomm Connect ships with G.729 codec. G.729 includes patents from several companies and is licensed by Sipro Lab Telecom. Sipro Lab Telecom is the authorized Intellectual Property Licensing Administrator for G.729 technology and patent pool.

*In a number of countries, the use of G.729 may require a license fee and/or royalty fee.*

[[change-the-media-server-configuration]]
Change the Media Server configuration
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

* Go to $RESTCOMM_HOME/mediaserver/deploy/server-beans.xml
* Find the Signal processort factory section as shown below

....
<!-- Signal processor factory -->
<bean name="DSP" class="org.mobicents.media.server.component.DspFactoryImpl">
    <property name="codecs">
        <list value-type="java.lang.String">
            <value>org.mobicents.media.server.impl.dsp.audio.l16.Encoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.l16.Decoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.g711.alaw.Encoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.g711.alaw.Decoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.g711.ulaw.Encoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.g711.ulaw.Decoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.gsm.Encoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.gsm.Decoder</value>
        </list>
    </property>
</bean>
....

* Edit the section to add the G729 codec as shown below

[source,lang:default,decode:true]
----
<!-- Signal processor factory -->
<bean name="DSP" class="org.mobicents.media.server.component.DspFactoryImpl">
    <property name="codecs">
        <list value-type="java.lang.String">
            <value>org.mobicents.media.server.impl.dsp.audio.l16.Encoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.l16.Decoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.g711.alaw.Encoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.g711.alaw.Decoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.g711.ulaw.Encoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.g711.ulaw.Decoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.gsm.Encoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.gsm.Decoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.g729.Encoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.g729.Decoder</value>
        </list>
    </property>
</bean>
----

 

[[remove-the-g729-codec-from-the-media-server]]
remove the G729 codec from the media server
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

* Remove the g729 codec from the *$RESTCOMM_HOME/mediaserver/deploy/server-beans.xml* file

[source,lang:default,decode:true]
----
            <value>org.mobicents.media.server.impl.dsp.audio.g729.Encoder</value>
            <value>org.mobicents.media.server.impl.dsp.audio.g729.Decoder</value>
----
