#Makefile for Platform_User_Guide

XML_LANG	= en-US
# DOCNAME	= Platform_User_Guide
# PRODUCT	= FIX_ME!
BRAND		= JBoss
# DOC_TYPE	= Set

# Uncomment below 3 lines for a Distributed Set
#BOOKS = Platform_Installation_Guide JAIN_SLEE_Server_User_Guide
#BOOKS = Platform_Installation_Guide JAIN_SLEE_Server_User_Guide SIP_Servlets_Server_User_Guide Media_Server_User_Guide SIP_Presence_Service_User_Guide
#SET_REPO	= https://svn.devel.redhat.com/repos/ecs/JBoss_Communications_Platform/1.2.0/
#SET_REPO_TYPE	= SVN

#OTHER_LANGS	= as-IN bn-IN de-DE es-ES fr-FR gu-IN hi-IN it-IT ja-JP kn-IN ko-KR ml-IN mr-IN or-IN pa-IN pt-BR ru-RU si-LK ta-IN te-IN zh-CN zh-TW

# Extra Parameters start here

# Extra Parameters stop here
COMMON_CONFIG  = /usr/share/publican
include $(COMMON_CONFIG)/make/Makefile.common

# Uncomment below 2 lines for a Distributed Set
#pre:: get_books set_books
#clean:: clean_set_books

