= Restcomm RCML – Say

[[say]]
== Say
The *<Say>* verb is used to synthesize text to speech and play it to the remote party. The voices supported depends on the TTS Service provider plug-in. Below are the voices for our default TTS service provider plug-in which uses Acapela Voice and *VoiceRSS* (default) as a Service.

=== Say Attributes

[cols=",,",options="header",]
|======================================================================================================
|Name |Allowed Values |Default Value
|voice |man, woman |man
|language |bf, bp, en, en-gb,cf, cs, dan, fi es, fr, de, el, it, nl, no, pl, pt, ru, ar, ca, sv, tr |en
|loop |integer > 1 |1
|======================================================================================================

* *voice.* The 'voice' attribute allows you to select the gender of the voice used to synthesize the text to speech for playback.
* *language.* The 'language' attribute allows you pick a specific language for speech synthesis. RestComm currently supports languages 'bf' (Belgium-French), 'bp' (Brazilian-Portugues), 'en' (English), 'en-gb' (British-English), 'cf' (Canadian-French), 'cs' (Czech), 'dan' (Dannish), 'fi' (Finnish), 'es' (Spanish), 'fr' (French), 'de' (German), 'el' (Greek), 'it' (Italian), 'nl' (Netherlands-Dutch), 'no' (Norwegian), 'pl' (Polish), 'pt' (Portuguese), 'ru' (Russian), 'ar' (Saudi-Arabia Arabic), 'ca' (Spain Catalan), 'sv' (Swedish), and 'tr' (Turkish).
* *loop.* The 'loop' attribute specifies how many times you'd like the text repeated. Specifying '0' will cause the the <Say> verb to loop until the call is hung up.

=== Nesting

The *<Say>* verb can not have any other verbs or nouns nested. Only text.

=== Examples 
For an example of how to use the <Say> verb see below.

----
<Response>
    <Say>Hello World</Say>
</Response>
----

The example below shows how you can set the language, voice and loop parameters of the Say Verb

----
<Response>
        <Say voice="woman" language="fr" loop="3">Bienvenue à RestComm un projet parrainé par TeleStax</Say>
</Response>
----

=== Useful Information

* When translating text to speech, the Say verb will make assumptions about how to pronounce numbers, dates, times, amounts of money and other abbreviations.
* When saying numbers, '12345' will be spoken as "twelve thousand three hundred forty-five." Whereas '1 2 3 4 5' will be spoken as "one two three four five."