
= Document Conventions

This manual uses several conventions to highlight certain words and phrases and draw attention to specific pieces of information. 

In PDF and paper editions, this manual uses typefaces drawn from the https://fedorahosted.org/liberation-fonts/[Liberation Fonts] set.
The Liberation Fonts set is also used in HTML editions if the set is installed on your system.
If not, alternative but equivalent typefaces are displayed.
Note: Red Hat Enterprise Linux 5 and later includes the Liberation Fonts set by default. 

== Typographic Conventions

Four typographic conventions are used to call attention to specific words and phrases.
These conventions, and the circumstances they apply to, are as follows. 

`Mono-spaced Bold`		

Used to highlight system input, including shell commands, file names and paths.
Also used to highlight key caps and key-combinations.
For example: 

[quote]
To see the contents of the file [path]_my_next_bestselling_novel_ in your current working directory, enter the `cat my_next_bestselling_novel` command at the shell prompt and press kbd:[Enter] to execute the command. 

The above includes a file name, a shell command and a key cap, all presented in Mono-spaced Bold and all distinguishable thanks to context. 

Key-combinations can be distinguished from key caps by the hyphen connecting each part of a key-combination.
For example: 

____
Press kbd:[Enter] to execute the command. 

Press  to switch to the first virtual terminal.
Press  to return to your X-Windows session. 
____

The first sentence highlights the particular key cap to press.
The second highlights two sets of three key caps, each set pressed simultaneously. 

If source code is discussed, class names, methods, functions, variable names and returned values mentioned within a paragraph will be presented as above, in `Mono-spaced Bold`.
For example: 

[quote]
File-related classes include [class]`filesystem` for file systems, [class]`file` for files, and [class]`dir` for directories.
Each class has its own associated set of permissions. 

[app]`Proportional Bold`		

This denotes words or phrases encountered on a system, including application names; dialogue box text; labelled buttons; check-box and radio button labels; menu titles and sub-menu titles.
For example: 

____
Choose menu:System > Preferences > Mouse[] from the main menu bar to launch [app]`Mouse Preferences`.
In the [label]#Buttons# tab, click the [label]#Left-handed mouse# check box and click btn:[Close] to switch the primary mouse button from the left to the right (making the mouse suitable for use in the left hand). 

To insert a special character into a [app]`gedit` file, choose menu:Applications > Accessories > Character Map[] from the main menu bar.
Next, choose menu:Search > Find[] from the [app]`Character Map` menu bar, type the name of the character in the [label]#Search# field and click btn:[Next].
The character you sought will be highlighted in the [label]#Character Table#.
Double-click this highlighted character to place it in the [label]#Text to copy# field and then click the btn:[Copy] button.
Now switch back to your document and choose menu:Edit > Paste[] from the [app]`gedit` menu bar. 
____

The above text includes application names; system-wide menu names and items; application-specific menu names; and buttons and text found within a GUI interface, all presented in Proportional Bold and all distinguishable by context. 

Note the menu:>[] shorthand used to indicate traversal through a menu and its sub-menus.
This is to avoid the difficult-to-follow 'Select  from the menu:Preferences[] sub-menu in the menu:System[] menu of the main menu bar' approach. 

`Mono-spaced Bold Italic` or [app]`Proportional Bold Italic`		

Whether Mono-spaced Bold or Proportional Bold, the addition of Italics indicates replaceable or variable text.
Italics denotes text you do not input literally or displayed text that changes depending on circumstance.
For example: 

____
To connect to a remote machine using ssh, type `ssh username@domain.name` at a shell prompt.
If the remote machine is [path]_example.com_ and your username on that machine is john, type `ssh john@example.com`. 

The `mount -o remount file-system` command remounts the named file system.
For example, to remount the [path]_/home_ file system, the command is `mount -o remount /home`. 

To see the version of a currently installed package, use the `rpm -q package` command.
It will return a result as follows: `package-version-release`. 
____

Note the words in bold italics above &mdash;username, domain.name, file-system, package, version and release.
Each word is a placeholder, either for text you enter when issuing a command or for text displayed by the system. 

Aside from standard usage for presenting the title of a work, italics denotes the first use of a new and important term.
For example: 

[quote]
When the Apache HTTP Server accepts requests, it dispatches child processes or threads to handle them.
This group of child processes or threads is known as a [term]_server-pool_.
Under Apache HTTP Server 2.0, the responsibility for creating and maintaining these server-pools has been abstracted to a group of modules called [term]_Multi-Processing Modules_ ([term]_MPMs_). Unlike other modules, only one module from the MPM group can be loaded by the Apache HTTP Server. 

== Pull-quote Conventions

Two, commonly multi-line, data types are set off visually from the surrounding text. 

Output sent to a terminal is set in `Mono-spaced Roman` and presented thus: 

----

books        Desktop   documentation  drafts  mss    photos   stuff  svn
books_tests  Desktop1  downloads      images  notes  scripts  svgs
----

Source-code listings are also set in `Mono-spaced Roman` but are presented and highlighted as follows: 

[source,java]
----

package org.jboss.book.jca.ex1;

import javax.naming.InitialContext;

public class ExClient
{
   public static void main(String args[]) 
       throws Exception
   {
      InitialContext iniCtx = new InitialContext();
      Object         ref    = iniCtx.lookup("EchoBean");
      EchoHome       home   = (EchoHome) ref;
      Echo           echo   = home.create();

      System.out.println("Created Echo");

      System.out.println("Echo.echo('Hello') = " + echo.echo("Hello"));
   }
   
}
----

== Notes and Warnings

Finally, we use three visual styles to draw attention to information that might otherwise be overlooked. 

.Note
[NOTE]
====
A note is a tip or shortcut or alternative approach to the task at hand.
Ignoring a note should have no negative consequences, but you might miss out on a trick that makes your life easier. 
====

.Important
[IMPORTANT]
====
Important boxes detail things that are easily missed: configuration changes that only apply to the current session, or services that need restarting before an update will apply.
Ignoring Important boxes won't cause data loss but may cause irritation and frustration. 
====

.Warning
[WARNING]
====
A Warning should not be ignored.
Ignoring warnings will most likely cause data loss. 
====