[[intro]]
= Restcomm Amazon S3 Integration

With Restcomm Amazon S3 Integration you can use Amazon S3 for recording storage.

Either if you use Record verb or you use Dial with record, if the Amazon S3 integrations is enabled, the recording will be uploaded to Amazon S3 bucket you specified.

== Configuration

To enable Amazon S3 integration check instructions here: <<../Restcomm-Advanced Automatic Configuration Options.adoc#amazons3,Amazon S3 configuration>>

== Advanced configuration

You can configure how Restcomm will treat the Amazon S3 URL of the uploaded recording by changing the security level at restcomm.xml:

[source,xml]
----
	<amazon-s3>
		<enabled>false</enabled>
		<bucket-name>restcomm-recordings</bucket-name>
		<folder></folder>
		<access-key></access-key>
		<security-key></security-key>
		<reduced-redundancy>false</reduced-redundancy>
		<minutes-to-retain-public-url>10</minutes-to-retain-public-url>
		<remove-original-file>true</remove-original-file>
		<bucket-region>us-east-1</bucket-region>
		<security-level>secure</security-level>
	</amazon-s3>
----


The Security level controls the details that the Recordings REST API will provide to the user and also how the user will access the wav file.

1. **NONE**: Recordings REST API response, will contain the S3_URI with no credentials. Restcomm will fetch and serve recording to the user if the FILE_URI of the Recording is used
2. **REDIRECT**: Recordings REST API response will NOT contain the S3_URI. Restcomm will create redirect response and recording will be served by Amazon S3 if the FILE_URI of the Recording is used
3. **SECURE**: Recordings REST API response will NOT contain the S3_URI. Restcomm will fetch and serve recording to the user if the FILE_URI of the Recording is used

Default value is **SECURE**
