You can run RestComm Docker image using the official Docker for OSX installation found at https://docs.docker.com/engine/installation/mac/ (more details on the issues at: https://github.com/restcomm/Restcomm-Docker/issues/10). Here's an alternative that works until those issues are fixed:

[[docker-linux-vm]]
Use a Linux Virtual Image to run Docker
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

* Install Virtual Box
* Install a Docker-capable linux distribution as a guest in the Virtual Box (in this example we installed Ubuntu Server 14.04)
* Shut down guest
* Setup networking for guest, use 'Bridged Adapter' setting. That will make the guest reachable in the local LAN (for example if host is 192.168.2.3, guest would most likely get 192.168.2.4) and you won't have to do any special port mapping
* Start up the guest
* Install latest docker inside the guest (https://docs.docker.com/engine/installation/ubuntulinux/)
* Download the latest docker image for RestComm `$ sudo docker pull restcomm/restcomm:latest`
* Start up the docker image using commands found above, in my case that I wanted a secure installation the command is:

[source,lang:default,decode:true]
----
sudo docker run -e SECURESSL="true" -e SSL_MODE="allowall" -e USE_STANDARD_PORTS="true" -e VOICERSS_KEY="VOICERSS_KEY_HERE" --name=restcomm -d -p 80:80 -p 443:443 -p 9990:9990 -p 5060:5060 -p 5061:5061 -p 5062:5062 -p 5063:5063 -p 5060:5060/udp -p 65000-65050:65000-65050/udp restcomm/restcomm:latest
----

* The RestComm installation is available from the host system at: `https://<guest_ip>/`
* You can use the Olympus WebRTC Web App at: `https://<guest_ip>/olympus`
