[[environment-variables]]
Environment variables
~~~~~~~~~~~~~~~~~~~~~

RestComm docker container provides the option to use a file to configure environment variables. These variable are used with the Restcomm Docker  RUN command.

* *ENVCONFURL* Set the URL for environment variables configuration file location/repository. (You can find examples of RestComm environment configuration files https://github.com/RestComm/Restcomm-Docker/tree/master/env_files[HERE])
* *REPOUSR* Set Username for environment variables configuration file Authentication if needed.
* *REPOPWRD* Set Password for environment variables configuration file Authentication if needed.

The RestComm docker image supports the same set of environment variables to configure the RestComm application.

===== The only main difference is that some prefixes need to be used dependent on where the corresponding variable is located at the configuration file of the RestComm binary.
Explanation:

- Variables that are located at "restcomm.conf" need to be prefixed with "RCBCONF_"
- Variables that are located at "advanced.conf" need to be prefixed with "RCADVCONF_"
- Variables that are used to configure RMS ("mediaserver.conf") need to be prefixed with "RMSCONF_"
- Variables that are docker specific only need to be prefixed with "EXTCONF_".
- Variables that are used to configure Load Balancer need to be prefixed with "LBCONF_".
- Variables that are set from the RUN command line to overwrite the ones set at the configuration file need to be prefixed with "CLI_".

Docker Specific variables:

===== RestComm Logs Configuration
* *EXTCONF_RESTCOMM_LOGS* Base path where all RestComm related logs will be placed.
* *EXTCONF_RESTCOMM_TRACE_LOG* Set the location were to store network trace logs (pcap files)
* *EXTCONF_MEDIASERVER_LOGS_LOCATION* Set the location were to store Mediaserver logs.

===== Other
* *EXTCONF_RVD_PORT* Used when port mapping at docker is not the default (e.g: -p 445:443).

.Related Documentation

* Documentation for RestComm configuration can be found http://documentation.telestax.com/core/media_server/Media_Server_User_Guide.html#_ctms_configuring_the_media_server[HERE]
As well short description of the configuration options can be found at restcomm.conf https://raw.githubusercontent.com/RestComm/Restcomm-Connect/master/restcomm/configuration/config-scripts/as7-config-scripts/restcomm/restcomm.conf[HERE] & advanced.conf https://raw.githubusercontent.com/RestComm/Restcomm-Connect/master/restcomm/configuration/config-scripts/as7-config-scripts/restcomm/advanced.conf[HERE] at "RESTCOMM_PATH/bin/restcomm".
* Documentation for RMS configuration can be found http://documentation.telestax.com/core/media_server/Media_Server_User_Guide.html#_ctms_configuring_the_media_server[HERE]

---
---

