= Restcomm API – Account

[[Accounts]]
== Accounts

Accounts and sub-accounts are useful for things like segmenting phone numbers and usage data for your users and controlling access to data.

=== Account Resource URI

*/2012-04-24/Accounts/\{AccountSid}*

*/2012-04-24/Accounts/\{EmailAddress}*

Both the Account `sid` and the `email_address` field can be used to access an account.

=== Resource Properties

[cols=",",options="header",]
|=========================================================================================================================
|Property |Description
|Sid |A string that uniquely identifies this account.
|DateCreated |The date that this account was created.
|DateUpdated |The date that this account was last updated.
|FriendlyName |A description of this account, up to 64 characters long. By default the FriendlyName is your email address.
|EmailAddress | The email address of the account.
|Status |The status of this account. Possible values are active, suspended, and closed.
|AuthToken (not always present) |The authorization token for this account. This should not be shared.
|Uri |The URI for this account, relative to https://localhost:port/restcomm.
|=========================================================================================================================

=== Supported Operations

==== *HTTP GET*

Returns the representation of an Account resource, including the properties above.

==== Credentials

Both _Password_ and _AuthToken_ credentials can be used to retrieve an account.

==== *HTTP POST/PUT*

Modifies an Account resource and returns the representation, including the properties above. Below you will find a list of optional parameters.

==== Request Parameters

[cols=",",options="header",]
|==============================================================================================
|Parameter |Description
|FriendlyName |A description of this account, up to 64 characters long.
|Status |The status of this account. Possible values are active, suspended, and closed.
|Password |A password that will be used to generate the AuthToken for the new Account resource.
|==============================================================================================

==== Credentials

Only _Password_ credentials are allowed for PUT/POST operations.

==== *AuthToken Reset*

*POST /2012-04-24/Accounts/{AccountSid}/resetAuthToken*

Resets the Authorization token for an account and returns the updated Account.

==== Credentials

Requires _Password_ credentials.

=== Credential types

Not all Account operations will work with the same type of credentials. Retrieving a single account will work both when _Auth Token_  or a _Password_ are used as credentials. More critical operations such as account _update_ or AuthToken _reset_ will require a _Password_.

==== AuthToken presense
Typically, most operations that return an Account won't include the AuthToken property in the response. There are two cases however when the AuthToken is present.

1. Retrieving one's own account using _Password_ credentials. 'Own' here means that the account SID in the credentials is the same as the SID of the account that is requested.

2. Account's AuthToken reset.

=== Use cases

==== **Get information about the default account**

....
curl -X GET  https://ACae6e420f425248d6a26948c17a9e2acf:77f8c12cc7b8f8423e5c38b035249166@127.0.0.1:8080/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf
....

This returns
----
<RestcommResponse>
  <Account>
    <Sid>ACae6e420f425248d6a26948c17a9e2acf</Sid>
    <FriendlyName>Default Administrator Account</FriendlyName>
    <Status>active</Status>
    <Type>Full</Type>
    <DateCreated>2012-04-24T00:00:00.000-06:00</DateCreated>
    <DateUpdated>2012-04-24T00:00:00.000-06:00</DateUpdated>
    <Uri>/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf</Uri>
    <SubresourceUris>
      <AvailablePhoneNumbers>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/AvailablePhoneNumbers</AvailablePhoneNumbers>
      <Calls>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Calls</Calls>
      <Conferences>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Conferences</Conferences>
      <IncomingPhoneNumbers>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/IncomingPhoneNumbers</IncomingPhoneNumbers>
      <Notifications>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Notifications</Notifications>
      <OutgoingCallerIds>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/OutgoingCallerIds</OutgoingCallerIds>
      <Recordings>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Recordings</Recordings>
      <Sandbox>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Sandbox</Sandbox>
      <SMSMessages>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/SMS/Messages</SMSMessages>
      <Transcriptions>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Transcriptions</Transcriptions>
    </SubresourceUris>
  </Account>
----

In order to include the _AuthToken_ in the response, use _Password_ credentials:
....
curl -X GET  https://ACae6e420f425248d6a26948c17a9e2acf:{password}@127.0.0.1:8080/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf
....
This will return:
----
<RestcommResponse>
  <Account>
    <Sid>ACae6e420f425248d6a26948c17a9e2acf</Sid>
    ...
    <AuthToken>77f8c12cc7b8f8423e5c38b035249166</AuthToken>
    ...
    <FriendlyName>Default Administrator Account</FriendlyName>
    <Status>active</Status>
    <Type>Full</Type>
    ...
  </Account>
----

==== **Change default account password**

To update an account you need to provide the SID of the account or the email address of the account (make sure you url escape the @ sign of the email address)

For example, update password using account sid:
....
curl -X PUT https://ACae6e420f425248d6a26948c17a9e2acf:77f8c12cc7b8f8423e5c38b035249166@127.0.0.1:8080/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf -d "Password=NewPassword"
....

And update password using email address of the account:

....
curl -X PUT https://ACae6e420f425248d6a26948c17a9e2acf:77f8c12cc7b8f8423e5c38b035249166@127.0.0.1:8080/restcomm/2012-04-24/Accounts/administrator%40company.com -d "Password=NewPassword"
....

NOTE: The above command uses the Account SID of the requestor, and the one below uses the Email Account. Note the administrator%40company.com is used instead of administrator@company.com . This is because using curl on the bash terminal doesn't parse the @ correctlyl. If you were to running on a browser, you can safely use the @ as the web browser will correctly handle it.

....
curl -X GET  https://administrator%40company.com:77f8c12cc7b8f8423e5c38b035249166@127.0.0.1:8080/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf
....

The above commands will print an output similar to the one below:

----
<RestcommResponse>
  <Account>
    <Sid>ACae6e420f425248d6a26948c17a9e2acf</Sid>
    <FriendlyName>Default Administrator Account</FriendlyName>
    <Status>active</Status>
    <Type>Full</Type>
    <DateCreated>2012-04-24T00:00:00.000-06:00</DateCreated>
    <DateUpdated>2012-04-24T00:00:00.000-06:00</DateUpdated>
    <Uri>/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf</Uri>
    <SubresourceUris>
      <AvailablePhoneNumbers>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/AvailablePhoneNumbers</AvailablePhoneNumbers>
      <Calls>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Calls</Calls>
      <Conferences>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Conferences</Conferences>
      <IncomingPhoneNumbers>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/IncomingPhoneNumbers</IncomingPhoneNumbers>
      <Notifications>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Notifications</Notifications>
      <OutgoingCallerIds>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/OutgoingCallerIds</OutgoingCallerIds>
      <Recordings>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Recordings</Recordings>
      <Sandbox>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Sandbox</Sandbox>
      <SMSMessages>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/SMS/Messages</SMSMessages>
      <Transcriptions>/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Transcriptions</Transcriptions>
    </SubresourceUris>
  </Account>
----

[[Accounts_List]]
== Account List Resource

=== Account List Resource URI

*/2012-04-24/Accounts*

=== Supported Operations

**HTTP GET**

Returns the list representation of all the *Sub-Account* resources for this **Account**, including the properties above.

**HTTP POST**

Creates a new Sub-Account and returns the representation of the Sub-Account resource, including the properties above. Below you will find a list of required and optional parameters.  

=== Request Parameters

[cols=",",options="header",]
|==============================================================================================================================================================================================================================
|Parameter |Description
|EmailAddress(Required) |The email address to use for this account.
|FriendlyName |A description of this account, up to 64 characters long. Default, is your email address.
|Status |The status of this account. Default is active, possible values are active, suspended, and closed.
|Password(Required) |A password that will be used to generate the AuthToken for the new Account resource.
|Role(Required) |The security role that this Account resource will use. If no role is provided then the role of the account resource creating this will be inherited to the new Account resource and may compromise the system.
|==============================================================================================================================================================================================================================


[[sub-accounts]]
== Sub-Accounts

An account may have children accounts called _Sub-Accounts_. Parent accounts have access to their sub-accounts. You can read more about Sub-Accounts and Multi-tenancy http://docs.telestax.com/restcomm-multi-tenancy-and-managing-sub-accounts/[HERE].

{nbsp}

==== Create a new Sub-Account

To create a new sub-account under account `administrator@company.com`:

....
curl -X POST https://administrator%40company.com:{password}}@127.0.0.1:8080/restcomm/2012-04-24/Accounts/ -d "FriendlyName=MySubAccount" -d "EmailAddress=test@telestax.com" -d "Password=restcomm"
....

The response will be:
----
<RestcommResponse>
  <Account>
    <Sid>AC3b8f0dd2e5026abde018446cbb3b185d</Sid>
    <FriendlyName>MySubAccount</FriendlyName>
    <Status>active</Status>
    <Type>Full</Type>
    <DateCreated>2013-10-16T09:22:28.708-06:00</DateCreated>
    <DateUpdated>2013-10-16T09:22:28.712-06:00</DateUpdated>
    <AuthToken>53134d7a9914e2b47c8435ebdb50ded3</AuthToken>
    <Uri>/restcomm/2012-04-24/Accounts/AC3b8f0dd2e5026abde018446cbb3b185d</Uri>
    <SubresourceUris>
      <AvailablePhoneNumbers>/restcomm/2012-04-24/Accounts/AC3b8f0dd2e5026abde018446cbb3b185d/AvailablePhoneNumbers</AvailablePhoneNumbers>
      <Calls>/restcomm/2012-04-24/Accounts/AC3b8f0dd2e5026abde018446cbb3b185d/Calls</Calls>
      <Conferences>/restcomm/2012-04-24/Accounts/AC3b8f0dd2e5026abde018446cbb3b185d/Conferences</Conferences>
      <IncomingPhoneNumbers>/restcomm/2012-04-24/Accounts/AC3b8f0dd2e5026abde018446cbb3b185d/IncomingPhoneNumbers</IncomingPhoneNumbers>
      <Notifications>/restcomm/2012-04-24/Accounts/AC3b8f0dd2e5026abde018446cbb3b185d/Notifications</Notifications>
      <OutgoingCallerIds>/restcomm/2012-04-24/Accounts/AC3b8f0dd2e5026abde018446cbb3b185d/OutgoingCallerIds</OutgoingCallerIds>
      <Recordings>/restcomm/2012-04-24/Accounts/AC3b8f0dd2e5026abde018446cbb3b185d/Recordings</Recordings>
      <Sandbox>/restcomm/2012-04-24/Accounts/AC3b8f0dd2e5026abde018446cbb3b185d/Sandbox</Sandbox>
      <SMSMessages>/restcomm/2012-04-24/Accounts/AC3b8f0dd2e5026abde018446cbb3b185d/SMS/Messages</SMSMessages>
      <Transcriptions>/restcomm/2012-04-24/Accounts/AC3b8f0dd2e5026abde018446cbb3b185d/Transcriptions</Transcriptions>
    </SubresourceUris>
  </Account>
----

Note the following:

- The **SID**, Email and the *AuthToken* (see output below) of the sub-account can now be used instead of the Administrator's account
- The sub-account will inherit role/permissions from  its creator, in this case `administrator@company.com`. You can alter this bahavior by explicitly passing the _Role_ parameter.
- _Password_ credentials have been used. Sub-account creation is a critical operation and won't work with _AuthToken_ credentials.

{nbsp}

==== Get a single Sub-Account

To retrieve a sub-account using parent account credentials:

----
curl -X GET https://[primarySid]:[primaryAuthToken]@127.0.0.1:8080/restcomm/2012-04-24/Accounts/[secondarySid]/
----

{nbsp}

==== Get a list of all Sub-Accounts

To retrieve a list with all sub-accounts of a 'primary' parent account:

----
curl -X GET https://[primarySid]:[primaryAuthToken]@127.0.0.1:8080/restcomm/2012-04-24/Accounts/
----

{nbsp}

[[close-sub-accounts]]
==== Close a Sub-Account

To close an an account permanently:
----
curl -X PUT https://ACae6e420f425248d6a26948c17a9e2acf:{password}@127.0.0.1:8080/restcomm/2012-04-24/Accounts/AC3b8f0dd2e5026abde018446cbb3b185d -d "Status=closed"
----

When an account is closed access to the system through it is revoked and most of its resources are deleted. The actual account entity will remain present though.

[[delete-sub-accounts]]
=== Delete Sub-Accounts (deprecated)

.XML Account Deletion
----
curl -X DELETE https://ACae6e420f425248d6a26948c17a9e2acf:PWD@192.168.1.3:8080/restcomm/2012-04-24/Accounts/<Sub-Account-SID>
----

.JSON Account Deletion
----
curl -X DELETE https://ACae6e420f425248d6a26948c17a9e2acf:PWD@192.168.1.3:8080/restcomm/2012-04-24/Accounts.json/<Sub-Account-SID>.json
----

NOTE: Account deletion has been deprecated from the REST API. Both of these methods will return HTTP 405. You will need to **close** the account instead.
