= Restcomm API – Organizations

[[organizations]]
== Organizations

An Organization instance resource represents a real-world organization domain inside RestComm. This entity assumes the top level in RestComm's data model, being responsible for offering a personalised user experience, and turning multi-tenant environments even more sophisticated.

The Organizations concept allows to integrate with DNS resources and use the URL from each request to identify the Organization namespace. Once RestComm validates the Organization, only Accounts that belongs to this Organization will be allowed to interact with RestComm, assuming the informed URL as a private space.

RestComm comes with a default and mandatory Organization named as "Default Organization", required by this concept to properly manage exception cases.

Considering the access control executed by multi-tenancy, everybody can create a new Organization, only the Accounts that belongs to the Organization can read informations from it, and only the administrator of the Organization can update or delete this entity. Any attempt of access different than the one described above will be denied.

=== Organizations Resource URI

*2012-04-24/Organizations/\{OrganizationSid}*

=== Resource Properties

[cols=",",]
|=========================================================================================================
|PROPERTY |DESCRIPTION
|Sid |A string that uniquely identifies this Organization.
|DateCreated |The date when this Organization was created.
|DateUpdated |The date wher this Organization was last updated.
|FriendlyName |The name of this Organization.
|Namespace |The namespace domain for this Organization, that will be used in the URL.
|ApiVersion |Version of the API applied to this Organization.
|Uri |The URI for this Organization, relative to http://localhost:port/restcomm.
|=========================================================================================================

=== Supported Operations

*HTTP GET*

Returns the representation of an Organization resource, including the properties described on the table "Resource Properties".

*HTTP POST and PUT* 

Modifies an Organization resource and returns the representation, including the properties described on the table "Resource Properties". The table below describes a list of optional parameters.

==== Request Parameters

You may specify one or more of the following parameters to update this Organization’s respective properties:

[cols=",",]
|=========================================================================================================
|PROPERTY |DESCRIPTION
|FriendlyName |The name of this Organization.
|Namespace |The namespace domain for this Organization, that will be used in the URL. (Supported values: a lower case string without empty spaces)
|=========================================================================================================

*HTTP DELETE*

Remove the Organization from RestComm's database. All the Accounts that belongs to this Organization are first transported to the "Default Organization" before the exclusion of the given Organization.

If successful, returns an HTTP 204 response with no body.

== Organizations List

=== Organizations List Resource URI

*2012-04-24/Organizations*

=== Supported Operations

*HTTP GET*

Returns a list of Organization resource representations, each representing a organization present in the environment. (Returns more than one Organization only when using RestComm's Administrator account)

*List Filters*

Given the rules of multi-tenancy, the list of organizations is automatically filtered using the informed account to authenticate. The return will be only the Organization that the Account informed to authenticate belongs to, using a list format. If the Account used to authenticate is the RestComm's Administrator account, then all the organisations will be presented in the list.

*HTTP POST*

Create a new Organization resource with the information provided by the required and optional parameters described by the tables below.

=== Required Parameters

Your request must include exactly the following parameters:

[cols=",",]
|=========================================================================================================
|PROPERTY |DESCRIPTION
|FriendlyName |The name of this Organization.
|Namespace |The namespace domain for this Organization, that will be used in the URL. (Supported values: a lower case string without empty spaces)
|=========================================================================================================

=== Optional Parameters

Not supported.

*HTTP PUT*

Not supported.

*HTTP DELETE*

Not supported.

== Create an Organization

----
curl -X POST http://ACae6e420f425248d6a26948c17a9e2acf:f8b593f84593130c39700c11ee996c0e@127.0.0.1:8080/restcomm/2012-04-24/Organizations -d "FriendlyName=Organization FooBar" -d "Namespace=foobar" -d "ApiVersion=2012-04-24"
----

The output of the command will be similar to the one below

[source,lang:xhtml,decode:true]
----
<RestcommResponse>
  <Organization>
    <Sid>OR9a38a2f96bb14d618de8e6c0a1ad4ff7</Sid>
    <DateCreated>Sat, 7 May 2016 15:32:50 -0300</DateCreated>
    <DateUpdated>Sat, 7 May 2016 15:32:50 -0300</DateUpdated>
    <FriendlyName>Organization FooBar</FriendlyName>
    <Namespace>foobar</Namespace>
    <ApiVersion>2012-04-24</ApiVersion>
    <Uri>/restcomm/2012-04-24/Organizations/OR9a38a2f96bb14d618de8e6c0a1ad4ff7</Uri>
  </Organization>
</RestcommResponse>
----

== Update a Organization

----
curl -X POST http://ACae6e420f425248d6a26948c17a9e2acf:f8b593f84593130c39700c11ee996c0e@127.0.0.1:8080/restcomm/2012-04-24/Organizations/OR9a38a2f96bb14d618de8e6c0a1ad4ff7 -d "FriendlyName=Organization XPTO" -d "Namespace=xpto"
----

The output of the command will be similar to the one below

[source,lang:xhtml,decode:true]
----
<RestcommResponse>
  <Organization>
    <Sid>OR9a38a2f96bb14d618de8e6c0a1ad4ff7</Sid>
    <DateCreated>Sat, 7 May 2016 15:32:50 -0300</DateCreated>
    <DateUpdated>Sat, 7 May 2016 15:42:09 -0300</DateUpdated>
    <FriendlyName>Organization XPTO</FriendlyName>
    <Namespace>xpto</Namespace>
    <ApiVersion>2012-04-24</ApiVersion>
    <Uri>/restcomm/2012-04-24/Organizations/OR9a38a2f96bb14d618de8e6c0a1ad4ff7</Uri>
  </Organization>
</RestcommResponse>
----

== Delete a Organization

----
curl -X DELETE http://ACae6e420f425248d6a26948c17a9e2acf:f8b593f84593130c39700c11ee996c0e@127.0.0.1:8080/restcomm/2012-04-24/Organizations/OR9a38a2f96bb14d618de8e6c0a1ad4ff7
----

No output for DELETE operation.

== Get a List of available Organizations

----
curl -X GET http://ACae6e420f425248d6a26948c17a9e2acf:f8b593f84593130c39700c11ee996c0e@127.0.0.1:8080/restcomm/2012-04-24/Organizations.json
----

The output of the command will be similar to the one below

----
[
  {
    "sid": "OR3c653e5a1131477dbf11bd9594d5b3fd",
    "date_created": "Sat, 7 May 2016 15:46:37 -0300",
    "date_updated": "Sat, 7 May 2016 15:46:37 -0300",
    "friendly_name": "Organization FooBar",
    "namespace": "foobar",
    "api_version": "2012-04-24",
    "uri": "/restcomm/2012-04-24/Organizations/OR3c653e5a1131477dbf11bd9594d5b3fd.json"
  },
  {
    "sid": "ORec3515ebea5243b6bde0444d84b05b80",
    "date_created": "Thu, 4 Aug 2016 11:37:00 -0300",
    "date_updated": "Thu, 4 Aug 2016 11:37:00 -0300",
    "friendly_name": "Default Organization",
    "namespace": "default",
    "api_version": "2012-04-24",
    "uri": "/restcomm/2012-04-24/Organizations/ORec3515ebea5243b6bde0444d84b05b80.json"
  }
]
----

(Note: The list above was obtained using the RestComm's Administrator credentials, if another Account was used, the list would have only the Organization that the Account belongs to.)
